from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select

driver = webdriver.Chrome()
driver.get("http://tools.iedb.org/conservancy/")

peptides = """YLQPRTFLL
FIAGLIAIV
VLNDILSRL
VLYENQKLI
RLQSLQTYV
KIADYNYKL
RLDKVEAEV
WTFGAGAAL
IIRGWIFGT
FVSNGTHWF
"""
peptide_box = WebDriverWait(driver, 10).until(
    EC.presence_of_element_located((By.NAME, "epitope_sequence"))
)
peptide_box.send_keys(peptides)

sequence = """>SARS2 spike glycoprotein\nMFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFSNVTWFHAIHVSGTNGTKRFDNPVLPFNDGVYFASTEKSNIIRGWIFGTTLDSKTQSLLIVNNATNVVIKVCEFQFCNDPFLGVYYHKNNKSWMESEFRVYSSANNCTFEYVSQPFLMDLEGKQGNFKNLREFVFKNIDGYFKIYSKHTPINLVRDLPQGFSALEPLVDLPIGINITRFQTLLALHRSYLTPGDSSSGWTAGAAAYYVGYLQPRTFLLKYNENGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLTGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITPGTNTSNQVAVLYQDVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEHVNNSYECDIPIGAGICASYQTQTNSPRRARSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTISVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLNRALTGIAVEQDKNTQEVFAQVKQIYKTPPIKDFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDCLGDIAARDLICAQKFNGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAMQMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNQNAQALNTLVKQLSSNFGAISSVLNDILSRLDKVEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPAICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDPLQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDLQELGKYEQYIKWPWYIWLGFIAGLIAIVMVTIMLCCMTSCCSCLKGCCSCGSCCKFDEDDSEPVLKGVKLHYT
"""
sequence_box = driver.find_element(By.NAME, "protein_sequence")
sequence_box.send_keys(sequence)

# seq_type_dropdown = Select(driver.find_element(By.NAME, "sequence_type"))
# seq_type_dropdown.select_by_visible_text("Nucleotide")

submit_button = driver.find_element(By.XPATH, '//input[@type="submit" and @value="Submit"]')
submit_button.click()

WebDriverWait(driver, 20).until(
    EC.presence_of_element_located((By.XPATH, "//table"))
)
results_table = driver.find_element(By.XPATH, "//table").get_attribute("outerHTML")

print("Conservancy Results Table HTML:\n", results_table)

rows = driver.find_elements(By.XPATH, "//table//tr")
for row in rows:
    cells = row.find_elements(By.TAG_NAME, "td")
    cell_texts = [cell.text for cell in cells]
    if cell_texts:
        print(cell_texts)

driver.quit()